/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) gen_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Printing routine */
#define PRINTF printf

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const int casadi_s1[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const int casadi_s2[5] = {1, 1, 0, 1, 0};

void casadi_copy(const casadi_real* x, int n, casadi_real* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

/* obs_cost:(i0[2],i1[16])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, *w3=w+18, w4, w5, w6, w7;
  /* #0: @0 = 3 */
  w0 = 3.;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 16, w1);
  /* #2: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @3 = input[0][0] */
  casadi_copy(arg[0], 2, w3);
  /* #5: @2 = @3[0] */
  for (rr=(&w2), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #6: @4 = @1[0] */
  for (rr=(&w4), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #7: @2 = (@2-@4) */
  w2 -= w4;
  /* #8: @4 = 4 */
  w4 = 4.;
  /* #9: @2 = pow(@2,@4) */
  w2  = pow(w2,w4);
  /* #10: @4 = @3[1] */
  for (rr=(&w4), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #11: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #12: @6 = @1[2] */
  for (rr=(&w6), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #13: @5 = (@5/@6) */
  w5 /= w6;
  /* #14: @4 = (@4-@5) */
  w4 -= w5;
  /* #15: @5 = 4 */
  w5 = 4.;
  /* #16: @4 = pow(@4,@5) */
  w4  = pow(w4,w5);
  /* #17: @2 = (@2+@4) */
  w2 += w4;
  /* #18: @2 = sqrt(@2) */
  w2 = sqrt( w2 );
  /* #19: @2 = (-@2) */
  w2 = (- w2 );
  /* #20: @2 = exp(@2) */
  w2 = exp( w2 );
  /* #21: @0 = (@0*@2) */
  w0 *= w2;
  /* #22: @2 = 3 */
  w2 = 3.;
  /* #23: @4 = @1[7] */
  for (rr=(&w4), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #24: @2 = (@2*@4) */
  w2 *= w4;
  /* #25: @4 = @3[0] */
  for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #26: @5 = @1[4] */
  for (rr=(&w5), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #27: @4 = (@4-@5) */
  w4 -= w5;
  /* #28: @5 = 4 */
  w5 = 4.;
  /* #29: @4 = pow(@4,@5) */
  w4  = pow(w4,w5);
  /* #30: @5 = @3[1] */
  for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #31: @6 = @1[5] */
  for (rr=(&w6), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #32: @7 = @1[6] */
  for (rr=(&w7), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #33: @6 = (@6/@7) */
  w6 /= w7;
  /* #34: @5 = (@5-@6) */
  w5 -= w6;
  /* #35: @6 = 4 */
  w6 = 4.;
  /* #36: @5 = pow(@5,@6) */
  w5  = pow(w5,w6);
  /* #37: @4 = (@4+@5) */
  w4 += w5;
  /* #38: @4 = sqrt(@4) */
  w4 = sqrt( w4 );
  /* #39: @4 = (-@4) */
  w4 = (- w4 );
  /* #40: @4 = exp(@4) */
  w4 = exp( w4 );
  /* #41: @2 = (@2*@4) */
  w2 *= w4;
  /* #42: @0 = (@0+@2) */
  w0 += w2;
  /* #43: @2 = 3 */
  w2 = 3.;
  /* #44: @4 = @1[11] */
  for (rr=(&w4), ss=w1+11; ss!=w1+12; ss+=1) *rr++ = *ss;
  /* #45: @2 = (@2*@4) */
  w2 *= w4;
  /* #46: @4 = @3[0] */
  for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #47: @5 = @1[8] */
  for (rr=(&w5), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #48: @4 = (@4-@5) */
  w4 -= w5;
  /* #49: @5 = 4 */
  w5 = 4.;
  /* #50: @4 = pow(@4,@5) */
  w4  = pow(w4,w5);
  /* #51: @5 = @3[1] */
  for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #52: @6 = @1[9] */
  for (rr=(&w6), ss=w1+9; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #53: @7 = @1[10] */
  for (rr=(&w7), ss=w1+10; ss!=w1+11; ss+=1) *rr++ = *ss;
  /* #54: @6 = (@6/@7) */
  w6 /= w7;
  /* #55: @5 = (@5-@6) */
  w5 -= w6;
  /* #56: @6 = 4 */
  w6 = 4.;
  /* #57: @5 = pow(@5,@6) */
  w5  = pow(w5,w6);
  /* #58: @4 = (@4+@5) */
  w4 += w5;
  /* #59: @4 = sqrt(@4) */
  w4 = sqrt( w4 );
  /* #60: @4 = (-@4) */
  w4 = (- w4 );
  /* #61: @4 = exp(@4) */
  w4 = exp( w4 );
  /* #62: @2 = (@2*@4) */
  w2 *= w4;
  /* #63: @0 = (@0+@2) */
  w0 += w2;
  /* #64: @2 = 3 */
  w2 = 3.;
  /* #65: @4 = @1[15] */
  for (rr=(&w4), ss=w1+15; ss!=w1+16; ss+=1) *rr++ = *ss;
  /* #66: @2 = (@2*@4) */
  w2 *= w4;
  /* #67: @4 = @3[0] */
  for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #68: @5 = @1[12] */
  for (rr=(&w5), ss=w1+12; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #69: @4 = (@4-@5) */
  w4 -= w5;
  /* #70: @5 = 4 */
  w5 = 4.;
  /* #71: @4 = pow(@4,@5) */
  w4  = pow(w4,w5);
  /* #72: @5 = @3[1] */
  for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #73: @6 = @1[13] */
  for (rr=(&w6), ss=w1+13; ss!=w1+14; ss+=1) *rr++ = *ss;
  /* #74: @7 = @1[14] */
  for (rr=(&w7), ss=w1+14; ss!=w1+15; ss+=1) *rr++ = *ss;
  /* #75: @6 = (@6/@7) */
  w6 /= w7;
  /* #76: @5 = (@5-@6) */
  w5 -= w6;
  /* #77: @6 = 4 */
  w6 = 4.;
  /* #78: @5 = pow(@5,@6) */
  w5  = pow(w5,w6);
  /* #79: @4 = (@4+@5) */
  w4 += w5;
  /* #80: @4 = sqrt(@4) */
  w4 = sqrt( w4 );
  /* #81: @4 = (-@4) */
  w4 = (- w4 );
  /* #82: @4 = exp(@4) */
  w4 = exp( w4 );
  /* #83: @2 = (@2*@4) */
  w2 *= w4;
  /* #84: @0 = (@0+@2) */
  w0 += w2;
  /* #85: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obs_cost(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void obs_cost_incref(void) {
}

CASADI_SYMBOL_EXPORT void obs_cost_decref(void) {
}

CASADI_SYMBOL_EXPORT int obs_cost_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int obs_cost_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* obs_cost_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obs_cost_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obs_cost_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obs_cost_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obs_cost_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 24;
  return 0;
}

int main_obs_cost(int argc, char* argv[]) {
  int *iw = 0;
  casadi_real w[43];
  const casadi_real* arg[4] = {w+0, w+2};
  casadi_real* res[2] = {w+18};
  int j;
  casadi_real* a = w;
  for (j=0; j<18; ++j) scanf("%lf", a++);
  int flag = obs_cost(arg, res, iw, w+19, 0);
  if (flag) return flag;
  const casadi_real* r = w+18;
  for (j=0; j<1; ++j) PRINTF("%g ", *r++);
  PRINTF("\n");
  return 0;
}


int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "obs_cost")==0) {
    return main_obs_cost(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'obs_cost'\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
