/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) gen_ ## ID
#endif

#include <time.h>
#include <Math.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Printing routine */
#define PRINTF printf

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

#undef exp
#define exp Math_Exp_flt64

#undef sqrt
#define sqrt Math_Sqrt_flt64

// #undef pow
// #define pow xPow


inline double xPow(double a, double b) {
  return Math_Exp2_flt64(b*Math_Log2_flt64(a));
}

inline double _fastPow(double a, double b) {
    union {
        double d;
        int x[2];
    } u = { a };
    u.x[1] = (int)(b * (u.x[1] - 1072632447) + 1072632447);
    u.x[0] = 0;
    return u.d;
}

inline double fastPow(double a, double b) {
  if (b < 0) {
    return 1.0 / _fastPow(a, -b);
  } else {
    return _fastPow(a, b);
  }
}

inline double _fastPrecisePow(double a, double b) {
  // calculate approximation with fraction of the exponent
  int e = (int) b;
  union {
    double d;
    int x[2];
  } u = { a };
  u.x[1] = (int)((b - e) * (u.x[1] - 1072632447) + 1072632447);
  u.x[0] = 0;

  // exponentiation by squaring with the exponent's integer part
  // double r = u.d makes everything much slower, not sure why
  double r = 1.0;
  while (e) {
    if (e & 1) {
      r *= a;
    }
    a *= a;
    e >>= 1;
  }

  return r * u.d;
}

inline double fastPrecisePow(double a, double b) {
  if (b < 0) {
    return 1.0 / _fastPrecisePow(a, -b);
  } else {
    return _fastPrecisePow(a, b);
  }
}



static const int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const int casadi_s1[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const int casadi_s2[5] = {1, 1, 0, 1, 0};

void casadi_copy(const casadi_real* x, int n, casadi_real* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

// /* obs_cost:(i0[2],i1[16])->(o0) */
// static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
//   casadi_real *rr, *ss;
//   casadi_real w0, *w1=w+1, w2, *w3=w+18, w4, w5, w6, w7;
//   /* #0: @0 = 3 */
//   w0 = 3.;
//   /* #1: @1 = input[1][0] */
//   casadi_copy(arg[1], 16, w1);
//   /* #2: @2 = @1[3] */
//   for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
//   /* #3: @0 = (@0*@2) */
//   w0 *= w2;
//   /* #4: @3 = input[0][0] */
//   casadi_copy(arg[0], 2, w3);
//   /* #5: @2 = @3[0] */
//   for (rr=(&w2), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
//   /* #6: @4 = @1[0] */
//   for (rr=(&w4), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
//   /* #7: @2 = (@2-@4) */
//   w2 -= w4;
//   /* #8: @4 = 4 */
//   w4 = 4.;
//   /* #9: @2 = pow(@2,@4) */
//   w2  = pow(w2,w4);
//   /* #10: @4 = @3[1] */
//   for (rr=(&w4), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
//   /* #11: @5 = @1[1] */
//   for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
//   /* #12: @6 = @1[2] */
//   for (rr=(&w6), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
//   /* #13: @5 = (@5/@6) */
//   w5 /= w6;
//   /* #14: @4 = (@4-@5) */
//   w4 -= w5;
//   /* #15: @5 = 4 */
//   w5 = 4.;
//   /* #16: @4 = pow(@4,@5) */
//   w4  = pow(w4,w5);
//   /* #17: @2 = (@2+@4) */
//   w2 += w4;
//   /* #18: @2 = sqrt(@2) */
//   w2 = sqrt( w2 );
//   /* #19: @2 = (-@2) */
//   w2 = (- w2 );
//   /* #20: @2 = exp(@2) */
//   w2 = exp( w2 );
//   /* #21: @0 = (@0*@2) */
//   w0 *= w2;
//   /* #22: @2 = 3 */
//   w2 = 3.;
//   /* #23: @4 = @1[7] */
//   for (rr=(&w4), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
//   /* #24: @2 = (@2*@4) */
//   w2 *= w4;
//   /* #25: @4 = @3[0] */
//   for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
//   /* #26: @5 = @1[4] */
//   for (rr=(&w5), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
//   /* #27: @4 = (@4-@5) */
//   w4 -= w5;
//   /* #28: @5 = 4 */
//   w5 = 4.;
//   /* #29: @4 = pow(@4,@5) */
//   w4  = pow(w4,w5);
//   /* #30: @5 = @3[1] */
//   for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
//   /* #31: @6 = @1[5] */
//   for (rr=(&w6), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
//   /* #32: @7 = @1[6] */
//   for (rr=(&w7), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
//   /* #33: @6 = (@6/@7) */
//   w6 /= w7;
//   /* #34: @5 = (@5-@6) */
//   w5 -= w6;
//   /* #35: @6 = 4 */
//   w6 = 4.;
//   /* #36: @5 = pow(@5,@6) */
//   w5  = pow(w5,w6);
//   /* #37: @4 = (@4+@5) */
//   w4 += w5;
//   /* #38: @4 = sqrt(@4) */
//   w4 = sqrt( w4 );
//   /* #39: @4 = (-@4) */
//   w4 = (- w4 );
//    #40: @4 = exp(@4)
//   w4 = exp( w4 );
//   /* #41: @2 = (@2*@4) */
//   w2 *= w4;
//   /* #42: @0 = (@0+@2) */
//   w0 += w2;
//   /* #43: @2 = 3 */
//   w2 = 3.;
//   /* #44: @4 = @1[11] */
//   for (rr=(&w4), ss=w1+11; ss!=w1+12; ss+=1) *rr++ = *ss;
//   /* #45: @2 = (@2*@4) */
//   w2 *= w4;
//   /* #46: @4 = @3[0] */
//   for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
//   /* #47: @5 = @1[8] */
//   for (rr=(&w5), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
//   /* #48: @4 = (@4-@5) */
//   w4 -= w5;
//   /* #49: @5 = 4 */
//   w5 = 4.;
//   /* #50: @4 = pow(@4,@5) */
//   w4  = pow(w4,w5);
//   /* #51: @5 = @3[1] */
//   for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
//   /* #52: @6 = @1[9] */
//   for (rr=(&w6), ss=w1+9; ss!=w1+10; ss+=1) *rr++ = *ss;
//   /* #53: @7 = @1[10] */
//   for (rr=(&w7), ss=w1+10; ss!=w1+11; ss+=1) *rr++ = *ss;
//   /* #54: @6 = (@6/@7) */
//   w6 /= w7;
//   /* #55: @5 = (@5-@6) */
//   w5 -= w6;
//   /* #56: @6 = 4 */
//   w6 = 4.;
//   /* #57: @5 = pow(@5,@6) */
//   w5  = pow(w5,w6);
//   /* #58: @4 = (@4+@5) */
//   w4 += w5;
//   /* #59: @4 = sqrt(@4) */
//   w4 = sqrt( w4 );
//   /* #60: @4 = (-@4) */
//   w4 = (- w4 );
//   /* #61: @4 = exp(@4) */
//   w4 = exp( w4 );
//   /* #62: @2 = (@2*@4) */
//   w2 *= w4;
//   /* #63: @0 = (@0+@2) */
//   w0 += w2;
//   /* #64: @2 = 3 */
//   w2 = 3.;
//   /* #65: @4 = @1[15] */
//   for (rr=(&w4), ss=w1+15; ss!=w1+16; ss+=1) *rr++ = *ss;
//   /* #66: @2 = (@2*@4) */
//   w2 *= w4;
//   /* #67: @4 = @3[0] */
//   for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
//   /* #68: @5 = @1[12] */
//   for (rr=(&w5), ss=w1+12; ss!=w1+13; ss+=1) *rr++ = *ss;
//   /* #69: @4 = (@4-@5) */
//   w4 -= w5;
//   /* #70: @5 = 4 */
//   w5 = 4.;
//   /* #71: @4 = pow(@4,@5) */
//   w4  = pow(w4,w5);
//   /* #72: @5 = @3[1] */
//   for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
//   /* #73: @6 = @1[13] */
//   for (rr=(&w6), ss=w1+13; ss!=w1+14; ss+=1) *rr++ = *ss;
//   /* #74: @7 = @1[14] */
//   for (rr=(&w7), ss=w1+14; ss!=w1+15; ss+=1) *rr++ = *ss;
//   /* #75: @6 = (@6/@7) */
//   w6 /= w7;
//   /* #76: @5 = (@5-@6) */
//   w5 -= w6;
//   /* #77: @6 = 4 */
//   w6 = 4.;
//   /* #78: @5 = pow(@5,@6) */
//   w5  = pow(w5,w6);
//   /* #79: @4 = (@4+@5) */
//   w4 += w5;
//   /* #80: @4 = sqrt(@4) */
//   w4 = sqrt( w4 );
//   /* #81: @4 = (-@4) */
//   w4 = (- w4 );
//   /* #82: @4 = exp(@4) */
//   w4 = exp( w4 );
//   /* #83: @2 = (@2*@4) */
//   w2 *= w4;
//   /* #84: @0 = (@0+@2) */
//   w0 += w2;
//   /* #85: output[0][0] = @0 */
//   if (res[0]) res[0][0] = w0;
//   return 0;
// }

/* obs_cost:(i0[2],i1[16])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, *w3=w+18, w4, w5, w6, w7;
  /* #0: @0 = 3 */
  w0 = 3.;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 16, w1);
  /* #2: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @3 = input[0][0] */
  casadi_copy(arg[0], 2, w3);
  /* #5: @2 = @3[0] */
  for (rr=(&w2), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #6: @4 = @1[0] */
  for (rr=(&w4), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #7: @2 = (@2-@4) */
  w2 -= w4;
  /* #8: @4 = sq(@2) */
  w4 = sq( w2 );
  /* #9: @4 = (@4*@2) */
  w4 *= w2;
  /* #10: @4 = (@4*@2) */
  w4 *= w2;
  /* #11: @2 = @3[1] */
  for (rr=(&w2), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #12: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #13: @6 = @1[2] */
  for (rr=(&w6), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #14: @5 = (@5/@6) */
  w5 /= w6;
  /* #15: @2 = (@2-@5) */
  w2 -= w5;
  /* #16: @5 = sq(@2) */
  w5 = sq( w2 );
  /* #17: @5 = (@5*@2) */
  w5 *= w2;
  /* #18: @5 = (@5*@2) */
  w5 *= w2;
  /* #19: @4 = (@4+@5) */
  w4 += w5;
  /* #20: @4 = sqrt(@4) */
  w4 = sqrt( w4 );
  /* #21: @4 = (-@4) */
  w4 = (- w4 );
  /* #22: @4 = exp(@4) */
  w4 = exp( w4 );
  /* #23: @0 = (@0*@4) */
  w0 *= w4;
  /* #24: @4 = 3 */
  w4 = 3.;
  /* #25: @5 = @1[7] */
  for (rr=(&w5), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #26: @4 = (@4*@5) */
  w4 *= w5;
  /* #27: @5 = @3[0] */
  for (rr=(&w5), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #28: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #29: @5 = (@5-@2) */
  w5 -= w2;
  /* #30: @2 = sq(@5) */
  w2 = sq( w5 );
  /* #31: @2 = (@2*@5) */
  w2 *= w5;
  /* #32: @2 = (@2*@5) */
  w2 *= w5;
  /* #33: @5 = @3[1] */
  for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #34: @6 = @1[5] */
  for (rr=(&w6), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #35: @7 = @1[6] */
  for (rr=(&w7), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #36: @6 = (@6/@7) */
  w6 /= w7;
  /* #37: @5 = (@5-@6) */
  w5 -= w6;
  /* #38: @6 = sq(@5) */
  w6 = sq( w5 );
  /* #39: @6 = (@6*@5) */
  w6 *= w5;
  /* #40: @6 = (@6*@5) */
  w6 *= w5;
  /* #41: @2 = (@2+@6) */
  w2 += w6;
  /* #42: @2 = sqrt(@2) */
  w2 = sqrt( w2 );
  /* #43: @2 = (-@2) */
  w2 = (- w2 );
  /* #44: @2 = exp(@2) */
  w2 = exp( w2 );
  /* #45: @4 = (@4*@2) */
  w4 *= w2;
  /* #46: @0 = (@0+@4) */
  w0 += w4;
  /* #47: @4 = 3 */
  w4 = 3.;
  /* #48: @2 = @1[11] */
  for (rr=(&w2), ss=w1+11; ss!=w1+12; ss+=1) *rr++ = *ss;
  /* #49: @4 = (@4*@2) */
  w4 *= w2;
  /* #50: @2 = @3[0] */
  for (rr=(&w2), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #51: @6 = @1[8] */
  for (rr=(&w6), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #52: @2 = (@2-@6) */
  w2 -= w6;
  /* #53: @6 = sq(@2) */
  w6 = sq( w2 );
  /* #54: @6 = (@6*@2) */
  w6 *= w2;
  /* #55: @6 = (@6*@2) */
  w6 *= w2;
  /* #56: @2 = @3[1] */
  for (rr=(&w2), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #57: @5 = @1[9] */
  for (rr=(&w5), ss=w1+9; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #58: @7 = @1[10] */
  for (rr=(&w7), ss=w1+10; ss!=w1+11; ss+=1) *rr++ = *ss;
  /* #59: @5 = (@5/@7) */
  w5 /= w7;
  /* #60: @2 = (@2-@5) */
  w2 -= w5;
  /* #61: @5 = sq(@2) */
  w5 = sq( w2 );
  /* #62: @5 = (@5*@2) */
  w5 *= w2;
  /* #63: @5 = (@5*@2) */
  w5 *= w2;
  /* #64: @6 = (@6+@5) */
  w6 += w5;
  /* #65: @6 = sqrt(@6) */
  w6 = sqrt( w6 );
  /* #66: @6 = (-@6) */
  w6 = (- w6 );
  /* #67: @6 = exp(@6) */
  w6 = exp( w6 );
  /* #68: @4 = (@4*@6) */
  w4 *= w6;
  /* #69: @0 = (@0+@4) */
  w0 += w4;
  /* #70: @4 = 3 */
  w4 = 3.;
  /* #71: @6 = @1[15] */
  for (rr=(&w6), ss=w1+15; ss!=w1+16; ss+=1) *rr++ = *ss;
  /* #72: @4 = (@4*@6) */
  w4 *= w6;
  /* #73: @6 = @3[0] */
  for (rr=(&w6), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #74: @5 = @1[12] */
  for (rr=(&w5), ss=w1+12; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #75: @6 = (@6-@5) */
  w6 -= w5;
  /* #76: @5 = sq(@6) */
  w5 = sq( w6 );
  /* #77: @5 = (@5*@6) */
  w5 *= w6;
  /* #78: @5 = (@5*@6) */
  w5 *= w6;
  /* #79: @6 = @3[1] */
  for (rr=(&w6), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #80: @2 = @1[13] */
  for (rr=(&w2), ss=w1+13; ss!=w1+14; ss+=1) *rr++ = *ss;
  /* #81: @7 = @1[14] */
  for (rr=(&w7), ss=w1+14; ss!=w1+15; ss+=1) *rr++ = *ss;
  /* #82: @2 = (@2/@7) */
  w2 /= w7;
  /* #83: @6 = (@6-@2) */
  w6 -= w2;
  /* #84: @2 = sq(@6) */
  w2 = sq( w6 );
  /* #85: @2 = (@2*@6) */
  w2 *= w6;
  /* #86: @2 = (@2*@6) */
  w2 *= w6;
  /* #87: @5 = (@5+@2) */
  w5 += w2;
  /* #88: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #89: @5 = (-@5) */
  w5 = (- w5 );
  /* #90: @5 = exp(@5) */
  w5 = exp( w5 );
  /* #91: @4 = (@4*@5) */
  w4 *= w5;
  /* #92: @0 = (@0+@4) */
  w0 += w4;
  /* #93: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obs_cost(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void obs_cost_incref(void) {
}

CASADI_SYMBOL_EXPORT void obs_cost_decref(void) {
}

CASADI_SYMBOL_EXPORT int obs_cost_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int obs_cost_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* obs_cost_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obs_cost_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obs_cost_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obs_cost_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obs_cost_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 24;
  return 0;
}

double x[2] = {0.0, 0.0};
const double y[16] = {
    1.0, 1.0, 10.0, 0.5, -10.0, -10.0, 10.0, 0.5,
    -10.0, -10.0, 10.0, 0.5, -10.0, -10.0, 10.0, 0.5,
};

double obstacle_cost_maxiam(const int i) {
  x[0] += i * 0.0000001;
  double cost =
      3.0 *
      (pow(2.718281828459045, -sqrt(pow(x[0] - y[0], 4.0) +
                                    pow(x[1] - y[1], 4.0) / pow(y[2], 4.0))) *
           y[3] +
       pow(2.718281828459045, -sqrt(pow(x[0] - y[4], 4.0) +
                                    pow(x[1] - y[5], 4.0) / pow(y[6], 4.0))) *
           y[7] +
       pow(2.718281828459045, -sqrt(pow(x[0] - y[8], 4.0) +
                                    pow(x[1] - y[9], 4.0) / pow(y[10], 4.0))) *
           y[11] +
       pow(2.718281828459045, -sqrt(pow(x[0] - y[12], 4.0) +
                                    pow(x[1] - y[13], 4.0) / pow(y[14], 4.0))) *
           y[15]);
  return cost;
}

int main_obs_cost(int argc, char* argv[]) {
  int *iw = 0;
  casadi_real w[43];
  const casadi_real* arg[4] = {w+0, w+2};
  casadi_real* res[2] = {w+18};
  int j;
  casadi_real* a = w;
  // for (j=0; j<18; ++j) scanf("%lf", a++);
  a[0] = 0.0;
  a[1] = 0.0;
  for (j = 2; j < 18; j += 4) {
    if (2 == j) {
      a[j] = 1.0;
      a[j + 1] = 1.0;
      a[j + 2] = 10.0;
      a[j + 3] = 0.5;
      continue;
    }
    a[j] = -10.0;
    a[j+1] = -10.0;
    a[j+2] = 10.0;
    a[j+3] = 0.5;
  }

  //////////////////////////////////////////////////////////////////////////////
  //////////////////////////////////////////////////////////////////////////////
  const int iterations = 1000000;

  clock_t t;
  t = clock();

  int flag = 0;
  for (int i = 0; i < iterations; i = i + 1) {
    a[0] += i * 0.0000001;
    flag = obs_cost(arg, res, iw, w + 19, 0);
  }

  t = clock() - t;
  double time_taken = ((double)t)/CLOCKS_PER_SEC; // in seconds

  if (flag) return flag;
  const casadi_real* r = w+18;
  for (j=0; j<1; ++j) PRINTF("%g ", *r++);

  PRINTF("\ncasadi time: %f\n", time_taken);
  PRINTF("\n");

  //////////////////////////////////////////////////////////////////////////////
  //////////////////////////////////////////////////////////////////////////////
  t = clock();
  double result = 0.0;
  for (int i = 0; i < iterations; i = i + 1) {
    result = obstacle_cost_maxiam(i);
  }
  t = clock() - t;
  time_taken = ((double)t)/CLOCKS_PER_SEC; // in seconds

  PRINTF("%g ", result);
  PRINTF("\nmaxiam time: %f\n", time_taken);
  PRINTF("\n");

  return 0;
}


int main(int argc, char* argv[]) {
  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, -1.0), fastPow(2.718281828459045, -1.0));
  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, -40.0), fastPow(2.718281828459045, -40.0));
  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, 40.0), fastPow(2.718281828459045, 40.0));
  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, 10.0), fastPow(2.718281828459045, 10.0));
  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, 0.1), fastPow(2.718281828459045, 0.1));
  // fprintf(stdout, "%f, %f\n\n\n", pow(2.718281828459045, -0.1), fastPow(2.718281828459045, -0.1));

  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, -1.0), fastPrecisePow(2.718281828459045, -1.0));
  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, -40.0), fastPrecisePow(2.718281828459045, -40.0));
  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, 40.0), fastPrecisePow(2.718281828459045, 40.0));
  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, 10.0), fastPrecisePow(2.718281828459045, 10.0));
  // fprintf(stdout, "%f, %f\n", pow(2.718281828459045, 0.1), fastPrecisePow(2.718281828459045, 0.1));
  // fprintf(stdout, "%f, %f\n\n\n", pow(2.718281828459045, -0.1), fastPrecisePow(2.718281828459045, -0.1));

  fprintf(stdout, "%f, %f\n", pow(2.718281828459045, -1.0), xPow(2.718281828459045, -1.0));
  fprintf(stdout, "%f, %f\n", pow(2.718281828459045, -40.0), xPow(2.718281828459045, -40.0));
  fprintf(stdout, "%f, %f\n", pow(2.718281828459045, 40.0), xPow(2.718281828459045, 40.0));
  fprintf(stdout, "%f, %f\n", pow(2.718281828459045, 10.0), xPow(2.718281828459045, 10.0));
  fprintf(stdout, "%f, %f\n", pow(2.718281828459045, 0.1), xPow(2.718281828459045, 0.1));
  fprintf(stdout, "%f, %f\n\n\n", pow(2.718281828459045, -0.1), xPow(2.718281828459045, -0.1));

  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "obs_cost")==0) {
    return main_obs_cost(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'obs_cost'\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
